/**
 * @file flash_defs.hpp
 * @brief NAND flash definitions for the GD5F1GQ5xExxG chip
 *
 * @author Daniel Proano (dproano@purdue.edu)
 */

#pragma once

#define NAND_NUM_BLOCKS 1024u
#define NAND_PAGES_PER_BLOCK 64u
#define NAND_BYTES_PER_PAGE 2176u
#define NAND_PAGE_SIZE 2048u
#define NAND_SPARE_PAGE_SIZE (NAND_BYTES_PER_PAGE - NAND_PAGE_SIZE)
#define NAND_NUM_PAGES (NAND_PAGES_PER_BLOCK * NAND_NUM_BLOCKS)
#define NAND_NUM_BYTES_PER_BLOCK (NAND_PAGES_PER_BLOCK * NAND_BYTES_PER_PAGE)
#define NAND_NUM_BYTES (NAND_NUM_BYTES_PER_BLOCK * NAND_NUM_BLOCKS)

#define CMD_NAND_WRITE_ENABLE 0x06u
#define CMD_NAND_WRITE_DISABLE 0x04u
#define CMD_NAND_GET_FEATURES 0x0Fu
#define CMD_NAND_SET_FEATURES 0x1Fu
#define CMD_NAND_PAGE_READ 0x13u
#define CMD_NAND_READ_FROM_CACHE 0x03u
#define CMD_NAND_READ_FROM_CACHE_QUAD 0x6Bu
#define CMD_NAND_READ_FROM_CACHE_QUAD_IO 0xEBu
#define CMD_NAND_READ_ID 0x9Fu
#define CMD_NAND_PROGRAM_LOAD 0x02u 
#define CMD_NAND_PROGRAM_LOAD_QUAD 0x32u
#define CMD_NAND_PROGRAM_EXECUTE 0x10u
#define CMD_NAND_PROGRAM_LOAD_RANDOM 0x84u
#define CMD_NAND_PROGRAM_LOAD_RANDOM_QUAD 0xC4u
#define CMD_NAND_BLOCK_ERASE 0xD8u
#define CMD_NAND_RESET 0xFFu

#define FEATURE_ADDR_BLOCK_LOCK 0xA0u
#define FEATURE_ADDR_CONFIG 0xB0u
#define FEATURE_ADDR_STATUS_A 0xC0u
#define FEATURE_ADDR_STATUS_B 0xF0u

#define CONFIG_QE_BIT (1u << 0) 

#define FREQ_MAX 50'000'000
#define HAL_TIMEOUT 10000
#define WORST_CASE_PROGRAM_TIMEOUT 600
#define WORST_CASE_MEMORY_TIMEOUT 10'000
