; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = ststm32
framework = arduino

monitor_speed = 57600
monitor_echo = yes
monitor_filters = 
  send_on_enter
  log2file

build_unflags =
  -Os                ; don't compile for size

build_flags =
  -D SERIAL_RX_BUFFER_SIZE=1024 ; increase serial buffer size
  -D SERIAL_TX_BUFFER_SIZE=1024
  -Wl,-u,_printf_float
  -Wl,-u,_scanf_float
  -D USBCON
  -D USBD_USE_CDC
  -O3                  ; compile for speed
  

[env:flight_controller]
board = toad_h7 ; for now these are the same for EC and FC - we can split if needed

build_flags = 
 -D TOAD_FLIGHT_CONTROLLER_ONLY

build_src_filter =
  -<**/*.cpp>
  +<**/fc_**.cpp>

[env:engine_controller]
board = toad_h7

build_flags = 
 -D TOAD_ENGINE_CONTROLLER_ONLY

build_src_filter =
  -<**/*.cpp>
  +<**/ec_**.cpp>

; we can add the programming cores here as well